language: node_js
node_js:
  - node

cache:
  directories:
    - ./node_modules/
    - packages/playground/node_modules
    - packages/server/node_modules

script:
  - npm run lint
  - npm test -- --coverage

after_script:
  - npm run prepack

  # Remove the packages installed for development
  - npm prune --production

  - cd packages/playground/
  - npm install
  - npm ls
  - npm run deploy
