language: node_js
node_js:
  - node

cache:
  directories:
    - ./node_modules/

script:
  - npm run lint
  - npm test -- --coverage

  - npm run prepack

  # Get it into a state where only production dependencies are installed.
  - rm -rf node_modules/
  - npm install --only=production

after_script:
  - cd examples/playground/
  - npm install

  # Copy package to be consistent.
  - rm node_modules/nice-sharebase
  - mkdir node_modules/nice-sharebase
  - cp -r ../../{lib,node_modules,package.json} node_modules/nice-sharebase

  - npm ls
  - npm run deploy
