language: node_js
node_js:
  - node

cache:
  directories:
    - ./node_modules/
    - packages/playground/node_modules

script:
  - npm run lint
  - npm test -- --coverage

after_script:
  - npm run prepack

  # Remove the graphql installed for development
  - rm -rf node_modules/graphql

  - cd packages/playground/
  - npm install
  - npm run deploy
